//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityList.Qcrm {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Qcrm.QCRMWebServiceSoap")]
    public interface QCRMWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddLead(string firstName, string lastName, string company, string phone, string model, string title, string formurl, string pagetitle, string email, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLead", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddLeadAsync(string firstName, string lastName, string company, string phone, string model, string title, string formurl, string pagetitle, string email, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEntityList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEntityList(string fetchxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEntityList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEntityListAsync(string fetchxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEntityListt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetEntityListt(string fetchxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEntityListt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetEntityListtAsync(string fetchxml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QCRMWebServiceSoapChannel : EntityList.Qcrm.QCRMWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QCRMWebServiceSoapClient : System.ServiceModel.ClientBase<EntityList.Qcrm.QCRMWebServiceSoap>, EntityList.Qcrm.QCRMWebServiceSoap {
        
        public QCRMWebServiceSoapClient() {
        }
        
        public QCRMWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QCRMWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCRMWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCRMWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddLead(string firstName, string lastName, string company, string phone, string model, string title, string formurl, string pagetitle, string email, string country) {
            return base.Channel.AddLead(firstName, lastName, company, phone, model, title, formurl, pagetitle, email, country);
        }
        
        public System.Threading.Tasks.Task<string> AddLeadAsync(string firstName, string lastName, string company, string phone, string model, string title, string formurl, string pagetitle, string email, string country) {
            return base.Channel.AddLeadAsync(firstName, lastName, company, phone, model, title, formurl, pagetitle, email, country);
        }
        
        public System.Data.DataSet GetEntityList(string fetchxml) {
            return base.Channel.GetEntityList(fetchxml);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEntityListAsync(string fetchxml) {
            return base.Channel.GetEntityListAsync(fetchxml);
        }
        
        public string GetEntityListt(string fetchxml) {
            return base.Channel.GetEntityListt(fetchxml);
        }
        
        public System.Threading.Tasks.Task<string> GetEntityListtAsync(string fetchxml) {
            return base.Channel.GetEntityListtAsync(fetchxml);
        }
    }
}
